# Generated by Django 4.1 on 2022-09-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_question_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="end_date",
            field=models.DateTimeField(null=True, verbose_name="end date"),
        ),
    ]
